export const MENU_CATEGORIES = [
  'All',
  'Signature Roasts',
  'Single Origin Pour-Over',
  'Artisanal Pastries',
  'Cold Extractions',
];

export const MENU_ITEMS = [
  {
    id: 'caveno-01',
    name: 'Smoked Obsidian Espresso',
    category: 'Signature Roasts',
    price: 9.50,
    description: 'Double shot of dark roasted Ethiopian Yirgacheffe G1 micro-lot espresso, infused with dark cocoa nectar, bergamot oil, and smoked oak essence.',
    flavorNotes: ['Dark Chocolate', 'Bergamot', 'Smoked Oak'],
    origin: 'Guji, Ethiopia • 2,100m',
    calories: '15 kcal',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: true,
  },
  {
    id: 'caveno-02',
    name: 'Velvet Gold Pour-Over',
    category: 'Single Origin Pour-Over',
    price: 14.00,
    description: 'Rare Geisha single-origin slow drip over copper carafes. Finished with organic wildflower honey and edible 24k gold leaf flakes.',
    flavorNotes: ['Jasmine', 'Peach', 'Honeycomb'],
    origin: 'Boquete, Panama • 1,900m',
    calories: '25 kcal',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: true,
  },
  {
    id: 'caveno-03',
    name: 'Amber Honey Tart',
    category: 'Artisanal Pastries',
    price: 16.00,
    description: 'Dark Valrhona cocoa shortcrust, salted caramel ganache, roasted hazelnuts, topped with 24k gold leaf and spun honey glass.',
    flavorNotes: ['Salted Caramel', 'Roasted Hazelnut', '24k Gold'],
    origin: 'Valrhona Grand Cru • France',
    calories: '340 kcal',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: true,
  },
  {
    id: 'caveno-04',
    name: 'Nitro Obsidian Cold Brew',
    category: 'Cold Extractions',
    price: 11.00,
    description: '24-hour cold steeped Sumatran Mandheling infused with nitrogen gas for a velvety, stout-like head and dark molasses body.',
    flavorNotes: ['Dark Molasses', 'Cedarwood', 'Black Currant'],
    origin: 'Aceh, Sumatra • 1,600m',
    calories: '10 kcal',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: false,
  },
  {
    id: 'caveno-05',
    name: 'Truffle Cloud Cappuccino',
    category: 'Signature Roasts',
    price: 12.50,
    description: 'Silky micro-foamed steamed oat milk, double espresso ristretto, dusted with shaved Italian black truffle and Madagascar vanilla.',
    flavorNotes: ['Black Truffle', 'Vanilla Bean', 'Toasted Oat'],
    origin: 'Huila, Colombia • 1,850m',
    calories: '120 kcal',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: true,
  },
  {
    id: 'caveno-06',
    name: 'Kyoto Drip Espresso Tonic',
    category: 'Cold Extractions',
    price: 10.50,
    description: 'Slow-drip Kyoto cold extraction layered over artisanal botanical tonic water, fresh rosemary sprig, and dehydrated blood orange.',
    flavorNotes: ['Blood Orange', 'Quinine', 'Rosemary'],
    origin: 'Tarrazú, Costa Rica • 1,750m',
    calories: '45 kcal',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: false,
  },
  {
    id: 'caveno-07',
    name: 'Smoked Vanilla Brioche',
    category: 'Artisanal Pastries',
    price: 13.50,
    description: 'Freshly baked French butter brioche infused with bourbon vanilla bean custard, torched brown sugar crust, and smoked salt.',
    flavorNotes: ['Bourbon Vanilla', 'Smoked Butter', 'Caramel Crust'],
    origin: 'Normandy Butter • France',
    calories: '410 kcal',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: false,
  },
  {
    id: 'caveno-08',
    name: 'Kenya AA Peaberry Pour-Over',
    category: 'Single Origin Pour-Over',
    price: 13.00,
    description: 'Single-lot rare peaberry harvest featuring vibrant blackcurrant acidity, dark wine undertones, and sugarcane sweetness.',
    flavorNotes: ['Blackcurrant', 'Red Wine', 'Sugarcane'],
    origin: 'Nyeri, Kenya • 1,950m',
    calories: '5 kcal',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=800&auto=format&fit=crop',
    isChefSpecial: false,
  },
];
